### ISSUE TITLE
Moneybook Entity 생성

### ISSUE THREAD

**Issue by polycompo** [circleGiven/moneybook-server#2]
**Table: work**

|String|String|WorkTypeEntity|PaymentTypeEntity|MoneyTypeEntity|Date|Date|Data|
|---|---|---|---|---|---|---|---|
|id|name|type|paymentType|moneyType|targetTime|createdTime|updatedTime|

<br/>

**Table: work_type**

|String|String|
|---|---|
|id|name|

<br/>

**Table: payment_type**

|String|String|
|---|---|
|id|name|

<br/>

**Table: money_type**

|String|String|
|---|---|
|id|name|

**Comment by brandon-wonjune** [comment]
enum은 따로 테이블을 구성할 필요가없을것같음.

https://stackoverflow.com/questions/16140282/jpa-enumerated-types-mapping-best-approach
위 방법이 더 좋아보임

**Comment by brandon-wonjune** [comment]
entity PK는 LONG타입 으로 변경

https://jojoldu.tistory.com/251

**Comment by brandon-wonjune** [comment]
나중에 사용자가 직접 타입을 추가하는 경우를 생각하면 type entity를 구성하는것이 좋을것같음
그러므로 테이블은 기존처럼 필요하고, enum은 필요없음

**Comment by polycompo** [comment]
**Table: work**

|String|String|WorkTypeEntity|String|Date|Date|Data|
|---|---|---|---|---|---|---|
|id|name|type|categoryId|targetTime|createdTime|updatedTime|



**Table: category**

|Long|String|String|
|---|---|---|
|id|workType|category|
